commands = {'Datenbanken verwalten': {
    'Datenbank erstellen': {'command': 'CREATE DATABASE [database]', 'explanation': 'Erstellt eine neue Datenbank'},
    'Datenbank verwenden': {'command': 'USE [database]', 'explanation': 'Wechselt zur angegebenen Datenbank'},
    'Datenbanken anzeigen': {'command': 'SHOW DATABASES', 'explanation': 'Listet alle Datenbanken auf'},
    'Datenbank löschen': {'command': 'DROP DATABASE [database]', 'explanation': 'Löscht eine Datenbank'},
    'Datenbank mit Zeichensatz': {'command': 'CREATE DATABASE [database] CHARACTER SET utf8mb4',
        'explanation': 'Erstellt DB mit UTF-8 Zeichensatz'}}, 'Tabellen verwalten': {
    'Tabelle erstellen': {'command': 'CREATE TABLE [table] (id INT, name VARCHAR(50))',
        'explanation': 'Erstellt eine neue Tabelle'},
    'Spalte hinzufügen': {'command': 'ALTER TABLE [table] ADD COLUMN [email] VARCHAR(100)',
        'explanation': 'Fügt eine Spalte hinzu'},
    'Tabelle löschen': {'command': 'DROP TABLE [table]', 'explanation': 'Löscht eine Tabelle'},
    'Tabellenstruktur': {'command': 'DESCRIBE [table]', 'explanation': 'Zeigt die Struktur einer Tabelle'},
    'Tabellen auflisten': {'command': 'SHOW TABLES', 'explanation': 'Listet alle Tabellen in der aktuellen DB auf'}},
    'Daten bearbeiten': {'Daten einfügen': {'command': "INSERT INTO [table] VALUES (1, 'John')",
        'explanation': 'Fügt einen neuen Datensatz ein'},
        'Daten aktualisieren': {'command': "UPDATE [table] SET [name]='Mike' WHERE id=1",
            'explanation': 'Aktualisiert einen Datensatz'},
        'Daten löschen': {'command': 'DELETE FROM [table] WHERE id=1', 'explanation': 'Löscht einen Datensatz'},
        'Alle Daten löschen': {'command': 'TRUNCATE TABLE [table]', 'explanation': 'Löscht alle Daten in der Tabelle'},
        'Daten ersetzen': {'command': "REPLACE INTO [table] VALUES (1, 'John')",
            'explanation': 'Ersetzt oder fügt einen Datensatz ein'}}, 'Datenabfragen': {
        'Alle Daten auswählen': {'command': 'SELECT * FROM [table]',
            'explanation': 'Wählt alle Spalten und Zeilen aus'},
        'Spalten auswählen': {'command': 'SELECT [name], [email] FROM [table]',
            'explanation': 'Wählt bestimmte Spalten aus'},
        'Mit Bedingung': {'command': 'SELECT * FROM [table] WHERE id > 5',
            'explanation': 'Filtert Datensätze nach Bedingung'},
        'Sortieren': {'command': 'SELECT * FROM [table] ORDER BY [name] DESC',
            'explanation': 'Sortiert die Ergebnisse absteigend'},
        'Paginierung': {'command': 'SELECT * FROM [table] LIMIT 10 OFFSET 20',
            'explanation': 'Zeigt 10 Datensätze ab Position 20'}}, 'Joins': {
        'INNER JOIN': {'command': 'SELECT u.[name], o.[amount] FROM [table] u JOIN [table2] o ON u.id = o.user_id',
            'explanation': 'Nur übereinstimmende Datensätze'},
        'LEFT JOIN': {'command': 'SELECT u.[name], o.[amount] FROM [table] u LEFT JOIN [table2] o ON u.id = o.user_id',
            'explanation': 'Alle Benutzer, auch ohne Bestellungen'}, 'RIGHT JOIN': {
            'command': 'SELECT u.[name], o.[amount] FROM [table] u RIGHT JOIN [table2] o ON u.id = o.user_id',
            'explanation': 'Alle Bestellungen, auch ohne Benutzer'},
        'CROSS JOIN': {'command': 'SELECT u.[name], o.[amount] FROM [table] u CROSS JOIN [table2] o',
            'explanation': 'Alle möglichen Kombinationen'}}, 'Funktionen': {
        'Aggregatfunktionen': {'command': 'SELECT COUNT(*), AVG([column]), MAX([date]) FROM [table]',
            'explanation': 'Zählen, Durchschnitt, Maximum'},
        'Textfunktion': {'command': "SELECT CONCAT([first_name], ' ', [last_name]) AS full_name FROM [table]",
            'explanation': 'Text verkettung'},
        'Datumsfunktion': {'command': "SELECT DATE_FORMAT([created_at], '%Y-%m') AS month FROM [table2]",
            'explanation': 'Datumsformatierung'},
        'NULL-Behandlung': {'command': "SELECT IFNULL([email], 'no email') FROM [table]",
            'explanation': 'Behandlung von NULL-Werten'},
        'Gruppierung': {'command': 'SELECT SUM([amount]) FROM [table2] GROUP BY user_id',
            'explanation': 'Gruppierung und Summierung'}}, 'Index': {
        'Index erstellen': {'command': 'CREATE INDEX idx_name ON [table]([name])',
            'explanation': 'Erstellt einen Index auf die name-Spalte'},
        'Eindeutigen Index': {'command': 'CREATE UNIQUE INDEX idx_email ON [table]([email])',
            'explanation': 'Erstellt einen eindeutigen Index'},
        'Index löschen': {'command': 'DROP INDEX idx_name ON [table]', 'explanation': 'Löscht einen Index'},
        'Indizes anzeigen': {'command': 'SHOW INDEX FROM [table]',
            'explanation': 'Zeigt alle Indizes einer Tabelle an'},
        'Abfrageplan': {'command': "EXPLAIN SELECT * FROM [table] WHERE [name] = 'John'",
            'explanation': 'Zeigt wie die Abfrage ausgeführt wird'}}}